# Generated by Django 4.2.5 on 2023-09-27 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='origin_country_id',
            new_name='country_origin_id',
        ),
    ]
