# Generated by Django 4.2.5 on 2023-09-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='cliente_id',
        ),
        migrations.AddField(
            model_name='compra',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
