# Generated by Django 4.2.5 on 2023-10-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoría',
            new_name='categoria_id',
        ),
    ]
